# Generated by Django 5.1.3 on 2025-01-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='stat',
        ),
    ]
